options:
- name: "Version"
  groupId: "version"
  help: "Some help information"
  values:
    - name: "1.2"
      tabName: "1.2"
    - name: "1.1"
      tabName: "1.1"
- name: "Channel"
  groupId: "channel"
  help: "Some help information"
  values:
    - name: "Stable"
      tabName: "stable"
    - name: "Early-Access"
      tabName: "ea"
    - name: "Beta"
      tabName: "beta"
    - name: "Alpha"
      tabName: "alpha"
- name: "Setup"
  groupId: "setup"
  help: "Some help information"
  values:
    - name: "Shell"
      tabName: "shell"
    - name: "Docker"
      tabName: "docker"
    - name: "Kubernetes"
      tabName: "kubernetes"
combinations:
- tabs:
  - name: "Setup 1"
    linkName: "setup_1"
    templateName: "default"
  - name: "View 1"
    linkName: "view_1"
    templateName: "default"
    params:
      - type: "type"
  options:
  - name: "Version"
    value: "1.1"
  - name: "Channel"
    value: "Stable"
  - name: "Setup"
    value: "Shell"
- tabs:
  - name: "Setup 2"
    linkName: "setup_2"
    templateName: "default"
  - name: "View 2"
    linkName: "view_2"
    templateName: "default"
    params:
      - type: "type"
  options:
  - name: "Version"
    value: "1.1"
  - name: "Channel"
    value: "Early-Access"
  - name: "Setup"
    value: "Shell"

