version: '3.5'
services:
  frontend:
    build:
      target: frontend
    ports:
      - "80:8080"
    container_name: example-app-frontend
    volumes:
      - ./public:/app/public
      - run-php:/var/run/php
  backend:
    build:
      target: backend
    container_name: example-app-backend
    environment:
      APP_KEY: base64:GcPVmSxMZwsOJtNOJ9eVNNeU6B5buHuln93+w0TSvfE=
      APP_DEBUG: true
      LOG_CHANNEL: stderr
      LOG_STDERR_FORMATTER: "Monolog\\Formatter\\JsonFormatter"
      LOG_LEVEL: debug
    volumes:
      - .:/app
      - run-php:/var/run/php
  composer:
    build:
      target: backend
    command: composer install
    volumes:
        - .:/app
volumes:
  run-php:
