apiVersion: apps/v1
kind: Deployment
metadata:
  name: werf-guide-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: werf-guide-app
  template:
    metadata:
      labels:
        app: werf-guide-app
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: app
        image: {{ .Values.werf.image.app }}
        # [<snippet command>]
        command: ["node", "./bin/www"]
        # [<endsnippet command>]
        ports:
        - containerPort: 3000
        # [<snippet env>]
        env:
        - name: NODE_ENV
          value: production
        - name: LOG_LEVEL
          value: debug
        # [<endsnippet env>]
