version: '3.5'
services:
  frontend:
    build:
      target: frontend
    ports:
      - "80:8080"
    container_name: example-app-frontend
    volumes:
      - ./public:/app/public
      - run-php:/var/run/php
  backend:
    build:
      target: backend
    container_name: example-app-backend
    environment:
      APP_KEY: base64:GcPVmSxMZwsOJtNOJ9eVNNeU6B5buHuln93+w0TSvfE=
      APP_DEBUG: true
      LOG_CHANNEL: stderr
      LOG_STDERR_FORMATTER: "Monolog\\Formatter\\JsonFormatter"
      LOG_LEVEL: debug
      DB_HOST: mysql
      DB_DATABASE: werf-guide-app
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - .:/app
      - run-php:/var/run/php
    networks:
      - example-app
  composer:
      build:
          target: backend
      command: composer install
      volumes:
          - .:/app
  mysql:
    image: mysql:8
    container_name: example-app-mysql
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: werf-guide-app
    restart: always
    networks:
      - example-app
    volumes:
      - db-data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
volumes:
  run-php:
  db-data:
networks:
  example-app:
    driver: bridge
