name: Cleanup Docker registry
on:
  schedule:
    - cron:  '10 6 * * *'
  repository_dispatch:
    types: [cleanup]

env:
  WERF_ENV: "production"
  WERF_REPO: "ghcr.io/${{ github.repository_owner }}/werfio-guides"
  WERF_STAGES_STORAGE: "ghcr.io/werf/werfio-guides-stages"

jobs:
  cleanup:
    name: Cleanup
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Cleanup
        uses: werf/actions/cleanup@43075e4ab81952b181d33e125ef15b9c060a782e
        env:
          WERF_LOG_VERBOSE: "on"
          WERF_REPO_GITHUB_TOKEN: ${{ secrets.REGISTRY_CLEANUP_TOKEN }}
